// <auto-generated />
using System;
using CorePuntoVenta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CorePuntoVenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231111105859_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CorePuntoVenta.Domain.Administracion.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CAJA"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ORDENES"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Administracion.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_usuarios_sucursal_id");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@ml-grupo.com.mx",
                            Nombre = "Admin",
                            Password = "$2a$12$yRELEkrsM7oesblMcmu60uR67uxaNQAhd3cMU7ZthsnQmRQH6EIYe",
                            RolId = 1,
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Correo = "caja1@ml-grupo.com.mx",
                            Nombre = "Caja",
                            Password = "$2a$12$yRELEkrsM7oesblMcmu60uR67uxaNQAhd3cMU7ZthsnQmRQH6EIYe",
                            RolId = 2,
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 3,
                            Correo = "ordenes1@ml-grupo.com.mx",
                            Nombre = "Ordenes",
                            Password = "$2a$12$yRELEkrsM7oesblMcmu60uR67uxaNQAhd3cMU7ZthsnQmRQH6EIYe",
                            RolId = 3,
                            SucursalId = 1
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("EfectivoDisponible")
                        .HasColumnType("double precision")
                        .HasColumnName("efectivo_disponible");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("NumeroCaja")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_caja");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cajas");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_cajas_sucursal_id");

                    b.ToTable("cajas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfectivoDisponible = 0.0,
                            Hostname = "caja",
                            Ip = "192.168.0.2",
                            NumeroCaja = "1",
                            SucursalId = 1
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.Corte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<double>("MontoCorte")
                        .HasColumnType("double precision")
                        .HasColumnName("monto_corte");

                    b.Property<double>("MontoEnCaja")
                        .HasColumnType("double precision")
                        .HasColumnName("monto_en_caja");

                    b.Property<double>("MontoInicial")
                        .HasColumnType("double precision")
                        .HasColumnName("monto_inicial");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cortes");

                    b.HasIndex("CajaId")
                        .HasDatabaseName("ix_cortes_caja_id");

                    b.ToTable("cortes", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.ItemCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    b.Property<double>("Monto")
                        .HasColumnType("double precision")
                        .HasColumnName("monto");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("Movimiento")
                        .HasColumnType("integer")
                        .HasColumnName("movimiento");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items_caja");

                    b.HasIndex("CajaId")
                        .HasDatabaseName("ix_items_caja_caja_id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_items_caja_empleado_id");

                    b.ToTable("items_caja", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Clientes.Models.Abono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<float>("Monto")
                        .HasColumnType("real")
                        .HasColumnName("monto");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_abonos");

                    b.ToTable("abonos", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Clientes.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer")
                        .HasColumnName("direccion_id");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("DireccionId")
                        .HasDatabaseName("ix_clientes_direccion_id");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionId = 1,
                            NombreComercial = "AARON",
                            RazonSocial = "AARON",
                            Rfc = "GOMA971007BD8"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Clientes.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Adeudo")
                        .HasColumnType("real")
                        .HasColumnName("adeudo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<float>("Saldo")
                        .HasColumnType("real")
                        .HasColumnName("saldo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cuentas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cuentas_cliente_id");

                    b.ToTable("cuentas", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Direcciones.Models.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .HasColumnType("text")
                        .HasColumnName("colonia");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("NumeroExterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_externo");

                    b.Property<string>("NumeroInterior")
                        .HasColumnType("text")
                        .HasColumnName("numero_interior");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_direcciones");

                    b.ToTable("direcciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calle = "calle",
                            CodigoPostal = "09660",
                            Colonia = "Bugambilia",
                            NumeroExterno = "1",
                            NumeroInterior = "2"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Empleados.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_paterno");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_empleados_sucursal_id");

                    b.ToTable("empleados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "López",
                            ApellidoPaterno = "Hernandez",
                            Nombre = "Rogelio",
                            SucursalId = 1
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.EstatusOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_estatus_orden");

                    b.ToTable("estatus_orden", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "CREADA"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "PENDIENTE"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PAGADA"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.ItemOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("Kilos")
                        .HasColumnType("double precision")
                        .HasColumnName("kilos");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("double precision")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<double>("Total")
                        .HasColumnType("double precision")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items_orden");

                    b.HasIndex("OrdenId")
                        .HasDatabaseName("ix_items_orden_orden_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_items_orden_producto_id");

                    b.ToTable("items_orden", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleado_id");

                    b.Property<int>("EstatusOrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("estatus_orden_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<double>("Kilos")
                        .HasColumnType("double precision")
                        .HasColumnName("kilos");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<double>("Total")
                        .HasColumnType("double precision")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ordenes");

                    b.HasIndex("CajaId")
                        .HasDatabaseName("ix_ordenes_caja_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_ordenes_cliente_id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_ordenes_empleado_id");

                    b.HasIndex("EstatusOrdenId")
                        .HasDatabaseName("ix_ordenes_estatus_orden_id");

                    b.ToTable("ordenes", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.ReferenciaOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Folio")
                        .HasColumnType("integer")
                        .HasColumnName("folio");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefijo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_referecias_orden");

                    b.ToTable("referecias_orden", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Pagos.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_metodos_pago");

                    b.ToTable("metodos_pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "EFECTIVO"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "TARJETA DE CRÉDITO/DEBITO"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CHEQUE"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Pagos.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<double>("Cambio")
                        .HasColumnType("double precision")
                        .HasColumnName("cambio");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_id");

                    b.Property<double>("MontoRecibido")
                        .HasColumnType("double precision")
                        .HasColumnName("monto_recibido");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("CajaId")
                        .HasDatabaseName("ix_pagos_caja_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pagos_cliente_id");

                    b.HasIndex("MetodoPagoId")
                        .HasDatabaseName("ix_pagos_metodo_pago_id");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_pagos_venta_id");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Productos.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pollo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Marinado"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Productos.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("double precision")
                        .HasColumnName("precio_unitario");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nombre = "POLLO ADOBADO",
                            PrecioUnitario = 0.0
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer")
                        .HasColumnName("direccion_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sucursales");

                    b.HasIndex("DireccionId")
                        .HasDatabaseName("ix_sucursales_direccion_id");

                    b.ToTable("sucursales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionId = 1,
                            Nombre = "AZTECAS"
                        });
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ventas.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("Iva")
                        .HasColumnType("double precision")
                        .HasColumnName("iva");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<double>("Subtotal")
                        .HasColumnType("double precision")
                        .HasColumnName("subtotal");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<double>("Total")
                        .HasColumnType("double precision")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("OrdenId")
                        .HasDatabaseName("ix_ventas_orden_id");

                    b.HasIndex("SucursalId")
                        .HasDatabaseName("ix_ventas_sucursal_id");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Administracion.Models.Usuario", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Administracion.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.HasOne("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_sucursales_sucursal_id");

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.Caja", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cajas_sucursales_sucursal_id");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.Corte", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Cajas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cortes_cajas_caja_id");

                    b.Navigation("Caja");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.ItemCaja", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Cajas.Models.Caja", "Caja")
                        .WithMany("Items")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_caja_cajas_caja_id");

                    b.HasOne("CorePuntoVenta.Domain.Empleados.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_caja_empleados_empleado_id");

                    b.Navigation("Caja");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Clientes.Models.Cliente", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Direcciones.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clientes_direcciones_direccion_id");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Clientes.Models.Cuenta", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Clientes.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Empleados.Models.Empleado", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_sucursales_sucursal_id");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.ItemOrden", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Ordenes.Models.Orden", "Orden")
                        .WithMany("ItemsOrden")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_orden_ordenes_orden_id");

                    b.HasOne("CorePuntoVenta.Domain.Productos.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_orden_productos_producto_id");

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.Orden", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Cajas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordenes_cajas_caja_id");

                    b.HasOne("CorePuntoVenta.Domain.Clientes.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordenes_clientes_cliente_id");

                    b.HasOne("CorePuntoVenta.Domain.Empleados.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordenes_empleados_empleado_id");

                    b.HasOne("CorePuntoVenta.Domain.Ordenes.Models.EstatusOrden", "EstatusOrden")
                        .WithMany()
                        .HasForeignKey("EstatusOrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordenes_estatus_orden_estatus_orden_id");

                    b.Navigation("Caja");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("EstatusOrden");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Pagos.Models.Pago", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Cajas.Models.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_cajas_caja_id");

                    b.HasOne("CorePuntoVenta.Domain.Clientes.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_clientes_cliente_id");

                    b.HasOne("CorePuntoVenta.Domain.Pagos.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_metodos_pago_metodo_pago_id");

                    b.HasOne("CorePuntoVenta.Domain.Ventas.Models.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_ventas_venta_id");

                    b.Navigation("Caja");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Productos.Models.Producto", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Productos.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Direcciones.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sucursales_direcciones_direccion_id");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ventas.Models.Venta", b =>
                {
                    b.HasOne("CorePuntoVenta.Domain.Ordenes.Models.Orden", "Orden")
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_ordenes_orden_id");

                    b.HasOne("CorePuntoVenta.Domain.Sucursales.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_sucursales_sucursal_id");

                    b.Navigation("Orden");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Cajas.Models.Caja", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ordenes.Models.Orden", b =>
                {
                    b.Navigation("ItemsOrden");
                });

            modelBuilder.Entity("CorePuntoVenta.Domain.Ventas.Models.Venta", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
